### ISSUE TITLE
notarytool throws Unexpected end of JSON input

### ISSUE THREAD

**Issue by drale2k** [lando/notarize-action#26]
I was not able to make it working using notarytool, the default, as it was always throwing the following error during the notarization step:

```
Run lando/notarize-action@v2
Archiving Application
Notarizing with notarytool
Error: Notarization failed with an unexpected error: Unexpected end of JSON input
```

I got it working by switching the tool to altool:

```
...
with:
  product-path: dist/myapp.app
  appstore-connect-username: ${{ secrets.APPLE_ID }}
  appstore-connect-password: ${{ secrets.APPLE_ID_PASSWORD }}
  appstore-connect-team-id: XYZ
  tool: altool
```

Leaving this here in case anyone bumps his head for 30 mins like i did.
